/**
 * SKILL.md generation + the STALENESS STAMP — the single highest-value, lowest-risk feature the council flagged as
 * genuinely missing today (conin's build-skill.ts has no hash). The skill's instruction TEXT is never the source of
 * truth: a served endpoint is, and SKILL.md is GENERATED from a `contentHash`-pinned snapshot of it. The stamp
 * binds the artifact to that snapshot so drift (the served preprompt changing after a signature/mint) is
 * tool-detectable. Pure: the instructions snapshot is an INPUT — no fetch at generate time.
 */
import { createHash } from "node:crypto";

/** A short, stable content hash of an instructions snapshot. */
export function contentHash(instructions: string): string {
  return "sha256-" + createHash("sha256").update(instructions, "utf8").digest("hex").slice(0, 16);
}

export interface SkillRenderInput {
  name: string;
  description: string;
  /** the instruction snapshot (the served /v1/instructions content, pinned at generate time). */
  instructions: string;
  /** the URL the snapshot was taken from (recorded in the stamp; not fetched here). */
  source?: string;
  version?: string;
}

/**
 * Render a Claude SKILL.md: YAML frontmatter (name + description) + a GENERATED stamp carrying source, the
 * computed contentHash, and version — then the instructions body verbatim. Deterministic in its inputs.
 */
export function renderSkillMd(input: SkillRenderInput): string {
  const hash = contentHash(input.instructions);
  const stamp = [
    "<!-- GENERATED by @suluk/agents — DO NOT EDIT BY HAND. Re-run on release.",
    `     source: ${input.source ?? "(inline)"}`,
    `     contentHash: ${hash}`,
    `     version: ${input.version ?? "(unversioned)"} -->`,
  ].join("\n");
  const desc = input.description.replace(/"/g, '\\"');
  return `---\nname: ${input.name}\ndescription: "${desc}"\n---\n\n${stamp}\n\n${input.instructions}\n`;
}
