// CANDIDATE — generated by @suluk/shadcn (renderTableTsx). Not official OAS tooling.
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

type Row = Record<string, unknown>;

export function CategoryTable({ rows }: { rows: Row[] }) {
  return (
    <Table>
      <TableHeader>
        <TableRow>
            <TableHead>Id</TableHead>
            <TableHead>Name</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map((row, i) => (
          <TableRow key={i}>
              <TableCell>{String(row["id"] ?? "")}</TableCell>
              <TableCell>{String(row["name"] ?? "")}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
