/**
 * Loading SKELETONS for the generated views (saastarter-parity Phase 3; PARITY: "Suspense skeletons / perceived
 * performance"). A skeleton mirrors the SHAPE of a form/table/detail so the layout doesn't jump when data lands.
 * Pure string codegen over the shadcn <Skeleton> primitive; same idiom as render-form/render-table/render-detail.
 */
import type { FormSpec, TableSpec } from "./spec";

export interface RenderSkeletonOptions {
  /** React component name (default per view: GeneratedFormSkeleton / …TableSkeleton / …DetailSkeleton). */
  componentName?: string;
  /** placeholder row count for the table/detail skeleton (default 5 / fields). */
  rows?: number;
}

const SKELETON_IMPORT = `import { Skeleton } from "@/components/ui/skeleton";`;
const HEADER = (fn: string) => `// CANDIDATE — generated by @suluk/shadcn (${fn}). Not official OAS tooling.\n${SKELETON_IMPORT}\n`;

/** A form skeleton — one label+control placeholder per field, plus a submit-button placeholder. */
export function renderFormSkeletonTsx(spec: FormSpec, opts: RenderSkeletonOptions = {}): string {
  const name = opts.componentName ?? "GeneratedFormSkeleton";
  const blocks = spec.fields
    .map(() => `      <div className="space-y-2">\n        <Skeleton className="h-4 w-24" />\n        <Skeleton className="h-9 w-full" />\n      </div>`)
    .join("\n");
  return `${HEADER("renderFormSkeletonTsx")}
export function ${name}() {
  return (
    <div className="space-y-6">
${blocks || "      <Skeleton className=\"h-9 w-full\" />"}
      <Skeleton className="h-9 w-24" />
    </div>
  );
}
`;
}

/** A table skeleton — a header row of column placeholders + N body rows of cell placeholders. */
export function renderTableSkeletonTsx(spec: TableSpec, opts: RenderSkeletonOptions = {}): string {
  const name = opts.componentName ?? "GeneratedTableSkeleton";
  const colCount = Math.max(1, spec.columns.length);
  const rowCount = opts.rows ?? 5;
  const head = Array.from({ length: colCount }, () => `            <TableHead><Skeleton className="h-4 w-20" /></TableHead>`).join("\n");
  const cells = Array.from({ length: colCount }, () => `              <TableCell><Skeleton className="h-4 w-full" /></TableCell>`).join("\n");
  return `// CANDIDATE — generated by @suluk/shadcn (renderTableSkeletonTsx). Not official OAS tooling.
${SKELETON_IMPORT}
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export function ${name}({ rows = ${rowCount} }: { rows?: number }) {
  return (
    <Table>
      <TableHeader>
        <TableRow>
${head}
        </TableRow>
      </TableHeader>
      <TableBody>
        {Array.from({ length: rows }).map((_, i) => (
          <TableRow key={i}>
${cells}
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
`;
}

/** A detail skeleton — one label+value placeholder row per field. */
export function renderDetailSkeletonTsx(spec: FormSpec, opts: RenderSkeletonOptions = {}): string {
  const name = opts.componentName ?? "GeneratedDetailSkeleton";
  const rows = spec.fields
    .map(() => `      <div className="grid grid-cols-3 gap-2 py-2">\n        <Skeleton className="h-4 w-24" />\n        <Skeleton className="col-span-2 h-4 w-full" />\n      </div>`)
    .join("\n");
  return `${HEADER("renderDetailSkeletonTsx")}
export function ${name}() {
  return (
    <dl className="divide-y">
${rows || "      <Skeleton className=\"h-4 w-full\" />"}
    </dl>
  );
}
`;
}
