/**
 * {@link FormSpec} → a read-only DETAIL (show) view TSX (saastarter-parity Phase 3). The CRUD set had a form
 * (create/edit) + a table (list) but no show view; this is the read-only counterpart — a definition list of every
 * field's label + value. Pure string codegen, same idiom as render-form/render-table.
 */
import type { FormSpec, FieldSpec } from "./spec";

export interface RenderDetailOptions {
  /** React component name. Default "GeneratedDetail". */
  componentName?: string;
}

function escapeText(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\{/g, "&#123;").replace(/\}/g, "&#125;");
}
function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
}

/** How to display one field's value: booleans as Yes/No, everything else stringified (null/undefined → ""). */
function valueExpr(f: FieldSpec): string {
  const key = escapeAttr(f.name);
  if (f.widget === "switch" || f.widget === "checkbox") return `record["${key}"] ? "Yes" : "No"`;
  return `String(record["${key}"] ?? "")`;
}

/** Render a read-only shadcn detail (show) view from a {@link FormSpec}. Returns TSX source as a string. */
export function renderDetailTsx(spec: FormSpec, opts: RenderDetailOptions = {}): string {
  const componentName = opts.componentName ?? "GeneratedDetail";
  const rows = spec.fields
    .map((f) =>
      `      <div className="grid grid-cols-3 gap-2 py-2">
        <dt className="text-sm font-medium text-muted-foreground">${escapeText(f.label)}</dt>
        <dd className="col-span-2 text-sm">{${valueExpr(f)}}</dd>
      </div>`)
    .join("\n");

  const warningHeader =
    spec.warnings.length > 0
      ? `// CANDIDATE codegen warnings (honest losses, not dropped silently):\n` +
        spec.warnings.map((w) => `//   - ${w}`).join("\n") +
        "\n"
      : "";

  return `${warningHeader}// CANDIDATE — generated by @suluk/shadcn (renderDetailTsx). Not official OAS tooling.

export function ${componentName}({ record }: { record: Record<string, unknown> }) {
  return (
    <dl className="divide-y">
${rows || "      {/* no fields derived */}"}
    </dl>
  );
}
`;
}
