/**
 * {@link TableSpec} → shadcn/ui <Table> TSX.
 *
 * Pure string codegen. Emits the idiomatic shadcn table skeleton: a `<TableHeader>` with one `<TableHead>`
 * per column, and a `<TableBody>` that maps over a `rows` prop, one `<TableCell>` per column. The component
 * is generically typed `Row = Record<string, unknown>`; the caller supplies typed data when wiring it.
 */
import type { TableSpec } from "./spec";

export interface RenderTableOptions {
  /** React component name. Default "GeneratedTable". */
  componentName?: string;
}

/** Escape a string for a JSX text node. */
function escapeText(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\{/g, "&#123;").replace(/\}/g, "&#125;");
}

/** Escape a string for a double-quoted JSX attribute. */
function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
}

/** Render a shadcn <Table> component from a {@link TableSpec}. Returns TSX source as a string. */
export function renderTableTsx(spec: TableSpec, opts: RenderTableOptions = {}): string {
  const componentName = opts.componentName ?? "GeneratedTable";

  const headCells = spec.columns
    .map((c) => `            <TableHead>${escapeText(c.header)}</TableHead>`)
    .join("\n");

  const bodyCells = spec.columns
    .map((c) => `              <TableCell>{String(row["${escapeAttr(c.key)}"] ?? "")}</TableCell>`)
    .join("\n");

  // surface any descriptor warnings as a leading comment so losses are never silent
  const warningHeader =
    spec.warnings.length > 0
      ? `// CANDIDATE codegen warnings (honest losses, not dropped silently):\n` +
        spec.warnings.map((w) => `//   - ${w}`).join("\n") +
        "\n"
      : "";

  return `${warningHeader}// CANDIDATE — generated by @suluk/shadcn (renderTableTsx). Not official OAS tooling.
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

type Row = Record<string, unknown>;

export function ${componentName}({ rows }: { rows: Row[] }) {
  return (
    <Table>
      <TableHeader>
        <TableRow>
${headCells || "            {/* no columns derived */}"}
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map((row, i) => (
          <TableRow key={i}>
${bodyCells || "              {/* no columns derived */}"}
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
`;
}
