/**
 * The cockpit's action side — codegen that LANDS files. Every generator is a pure function over the v4 hub
 * document, reusing the projection packages (so the editor never reimplements a projection). The vscode shell
 * just writes the returned string to a file the user picks.
 */
import { parseDocument } from "@suluk/core";
import type { OpenAPIv4Document, SchemaOrRef } from "@suluk/core";
import { formSpec, tableSpec, renderFormTsx, renderTableTsx } from "@suluk/shadcn";
import { buildCycle } from "./cycle";

/** Entity names available for codegen (components.schemas). */
export function entityNames(doc: OpenAPIv4Document): string[] {
  return Object.keys(doc.components?.schemas ?? {});
}

function entitySchema(doc: OpenAPIv4Document, name: string): { schema: SchemaOrRef; defs: Record<string, SchemaOrRef> } {
  const schemas = (doc.components?.schemas ?? {}) as Record<string, SchemaOrRef>;
  const schema = schemas[name];
  if (!schema) throw new Error(`no entity '${name}' in components.schemas`);
  return { schema, defs: schemas };
}

/** Generate a shadcn form component (TSX) for an entity. */
export function generateForm(doc: OpenAPIv4Document, name: string): string {
  const { schema, defs } = entitySchema(doc, name);
  return renderFormTsx(formSpec(schema, { defs }), { componentName: `${name}Form`, schemaName: `${name}Schema` });
}

/** Generate a shadcn table component (TSX) for an entity. */
export function generateTable(doc: OpenAPIv4Document, name: string): string {
  const { schema, defs } = entitySchema(doc, name);
  return renderTableTsx(tableSpec(schema, { defs }), { componentName: `${name}Table` });
}

/**
 * Generate the Nano Stores client wiring. @suluk/nano-stores is a runtime helper (createApiStores(routes)),
 * so the "codegen" is a thin, honest scaffold: it wires the user's RouteContracts to a typed store client and
 * lists, in comments, the exact stores the cockpit derived from the current document.
 */
export function generateStoresModule(doc: OpenAPIv4Document, opts: { baseUrl?: string } = {}): string {
  const model = buildCycle(doc);
  const state = model.layers.find((l) => l.id === "state");
  const lines = (state?.items ?? []).map((i) => ` *   ${i.label.padEnd(24)} ${i.detail}`).join("\n");
  const baseUrl = opts.baseUrl ?? "/api";
  return `// CANDIDATE — generated by suluk-vscode. Not official OAS tooling.
//
// Nano Stores client for this API. @suluk/nano-stores projects your RouteContracts (the same ones your
// Hono server is derived from) into typed fetcher/mutator stores. Wire your contracts here:
//
// Stores derived from the current v4 document:
${lines || " *   (no operations)"}
//
import { createApiStores } from "@suluk/nano-stores";
import { routes } from "./routes"; // your @suluk/hono RouteContract[] (the single source)

export const api = createApiStores(routes, { baseUrl: ${JSON.stringify(baseUrl)} });

// Usage:
//   const $pet = api.fetchers.getPet({ petId: "123" });  // GET  → fetcher store
//   await api.mutators.createPet.mutate({ data: { name: "Rex", tags: [] } }); // non-GET → mutator
`;
}

/** Export the v4 document as pretty JSON (the canonical interchange artifact). */
export function exportV4Json(source: string): string {
  return JSON.stringify(parseDocument(source), null, 2);
}
