// Regenerate src/validate.standalone.js (an AOT, eval-free validator for the v4 meta-schema) so @suluk/core
// validates on Cloudflare Workers. Run after changing schema/v4-meta-schema.json: bun run scripts/gen-validator.ts
import Ajv from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { readFileSync, writeFileSync } from "node:fs";
const schema = JSON.parse(readFileSync(new URL("../schema/v4-meta-schema.json", import.meta.url), "utf8"));
const ajv = new (Ajv as unknown as typeof import("ajv/dist/2020").default)({ allErrors: true, strict: false, code: { source: true, esm: true } });
const validate = ajv.compile(schema);
const code = (standaloneCode as unknown as (a: unknown, v: unknown) => string)(ajv, validate);
writeFileSync(new URL("../src/validate.standalone.js", import.meta.url), "// @generated by scripts/gen-validator.ts — do not edit. AOT (ajv-standalone) v4 meta-schema validator.\n" + code);
console.log("wrote src/validate.standalone.js (", code.length, "bytes )");
