/**
 * Package the built app as a shadcn REGISTRY — the universal distribution format for the WHOLE stack, not
 * just UI. shadcn's `registry:file` items can carry arbitrary files (backend routes, the v4 schema, the DB
 * schema) to any target path, so each entity becomes ONE installable, self-contained vertical slice
 * (`npx shadcn add <item>`): its shadcn Form/Table components AND its backend wiring AND its schema. The
 * vscode cockpit manages these items, which is what makes the stack modular + installable end to end.
 *
 * Schema: https://ui.shadcn.com/schema/registry-item.json
 */
import type { BuiltApp } from "./fullstack";
import type { SchemaOrRef } from "@suluk/core";

export interface RegistryFile {
  path: string;
  content: string;
  /** registry:component | registry:lib | registry:file | registry:page | … */
  type: string;
  /** For registry:file — the install target path in the consumer project. */
  target?: string;
}

export interface RegistryItem {
  $schema: string;
  name: string;
  type: string;
  title: string;
  description: string;
  dependencies?: string[];
  registryDependencies?: string[];
  files: RegistryFile[];
}

export interface ShadcnRegistry {
  /** The registry index (registry.json): name + homepage + items[]. */
  index: { $schema: string; name: string; homepage: string; items: { name: string; type: string; title: string }[] };
  items: RegistryItem[];
}

const ITEM_SCHEMA = "https://ui.shadcn.com/schema/registry-item.json";
const lower = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

/** The shadcn UI primitives the generated Form/Table depend on (registryDependencies). */
const UI_DEPS = ["button", "form", "input", "label", "select", "switch", "table", "textarea"];

/** Generate the backend wiring module for one entity (a registry:file the consumer installs server-side). */
function serverModule(entity: string): string {
  const e = lower(entity);
  return `// CANDIDATE — generated by @suluk/builder. The backend slice for ${entity}, installable via shadcn.
import { Hono } from "hono";
import { mount } from "@suluk/hono";
import { crudRoutesFromSchema } from "@suluk/builder";
import schema from "./${e}.schema.json";

// CRUD RouteContracts for ${entity}, derived from its v4 Schema Object (the single source).
export const ${e}Routes = crudRoutesFromSchema(${JSON.stringify(entity)}, schema as unknown as import("@suluk/core").SchemaOrRef);

// A ready Hono app for this slice (mount onto your Worker / server).
export const ${e}App = mount(new Hono(), ${e}Routes);
`;
}

/**
 * Convert a BuiltApp into a shadcn registry: one "block" item per entity bundling its frontend components +
 * backend routes module + its v4 schema, plus one "page" item per generated page.
 */
export function toShadcnRegistry(app: BuiltApp, opts: { name?: string; homepage?: string } = {}): ShadcnRegistry {
  const name = opts.name ?? "suluk-app";
  const homepage = opts.homepage ?? "https://example.com";
  const componentByName = new Map(app.frontend.components.map((c) => [c.name, c.tsx]));
  const items: RegistryItem[] = [];

  // one full-stack block per entity
  for (const e of app.entities) {
    const formTsx = componentByName.get(`${e.name}Form`) ?? "";
    const tableTsx = componentByName.get(`${e.name}Table`) ?? "";
    const eLower = lower(e.name);
    items.push({
      $schema: ITEM_SCHEMA,
      name: `${eLower}-crud`,
      type: "registry:block",
      title: `${e.name} CRUD`,
      description: `Full-stack ${e.name} slice — shadcn Form + Table, the backend CRUD routes, and the v4 schema. One install, the whole vertical.`,
      dependencies: ["zod", "hono", "@suluk/hono", "@suluk/builder", "@suluk/nano-stores"],
      registryDependencies: UI_DEPS,
      files: [
        { path: `components/${e.name}Form.tsx`, type: "registry:component", content: formTsx },
        { path: `components/${e.name}Table.tsx`, type: "registry:component", content: tableTsx },
        { path: `server/${eLower}.schema.json`, type: "registry:file", target: `src/server/${eLower}.schema.json`, content: JSON.stringify(e.schema as SchemaOrRef, null, 2) },
        { path: `server/${eLower}.routes.ts`, type: "registry:file", target: `src/server/${eLower}.routes.ts`, content: serverModule(e.name) },
      ],
    });
  }

  // one page item per generated page
  for (const p of app.frontend.pages) {
    items.push({
      $schema: ITEM_SCHEMA,
      name: `${lower(p.name)}-page`,
      type: "registry:page",
      title: `${p.name} page`,
      description: `The ${p.name} page — composes the entity slices.`,
      registryDependencies: items.filter((i) => i.type === "registry:block").map((i) => i.name),
      files: [{ path: `app/${lower(p.name)}/page.tsx`, type: "registry:page", target: `src/app/${lower(p.name)}/page.tsx`, content: p.tsx }],
    });
  }

  return {
    index: {
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name,
      homepage,
      items: items.map((i) => ({ name: i.name, type: i.type, title: i.title })),
    },
    items,
  };
}
