/**
 * Render a page DSL document to a frontend page (TSX). A page composes sections; each section composes the
 * entity's Table/Form blocks (whose names ARE the generated shadcn component names). So the page resolves to
 * an ordered list of components, wired to the @suluk/nano-stores client. The header comment states the page's
 * contract — exactly what this tier was allowed to set — making the narrowing visible in the output.
 */
import type { DslDocument } from "./dsl";
import { isListSpec } from "./dsl";
import { resolveList } from "./resolve";
import type { Registry } from "./registry";

/** Ordered component names a page resolves to (section list → each section's block list → block===component). */
export function resolveComponents(page: DslDocument, reg: Registry): string[] {
  const sectionsSpec = page.params?.sections;
  const sectionNames = sectionsSpec && isListSpec(sectionsSpec) ? resolveList(sectionsSpec, undefined) : [];
  const components: string[] = [];
  for (const sn of sectionNames) {
    const section = reg.sections[sn];
    const blocksSpec = section?.params?.blocks;
    const blockNames = blocksSpec && isListSpec(blocksSpec) ? resolveList(blocksSpec, undefined) : [];
    components.push(...blockNames);
  }
  return components;
}

export function renderPageTsx(page: DslDocument, reg: Registry, opts: { baseUrl?: string } = {}): string {
  const components = resolveComponents(page, reg);
  const unique = [...new Set(components)];
  const imports = unique.map((c) => `import { ${c} } from "./components/${c}";`).join("\n");
  const body = components.length ? components.map((c) => `        <${c} />`).join("\n") : "        {/* no sections selected */}";
  const contract = Object.keys(page.params ?? {}).join(", ") || "(nothing)";
  const baseUrl = opts.baseUrl ?? "/api";

  return `// CANDIDATE — generated by @suluk/builder (renderPageTsx). Not official OAS tooling.
//
// Page "${page.name}" — composed from the Suluk cycle (sections → blocks → entity components), each wired to
// the @suluk/nano-stores client at ${JSON.stringify(baseUrl)}. CONTRACT for this tier: a page may set { ${contract} }
// and nothing deeper — the sections narrowed the rest away.
"use client";

${imports || "// (no components)"}

export function ${page.name}Page() {
  return (
    <main className="suluk-page">
      <div className="suluk-page__stack">
${body}
      </div>
    </main>
  );
}
`;
}
