/**
 * The Cloudflare provider. The Suluk stack is already Cloudflare-native, so this is an ADAPTER not a rewrite:
 *   - the Hono `app` is a valid Worker default export      → Workers
 *   - the data floor is sqlite-core                          → D1 (which IS SQLite)
 *   - the built frontend is static assets                    → the Worker's `assets` binding (SPA fallback)
 * generate() produces the files + the ordered wrangler steps; the host (the vscode extension) runs the steps
 * in a terminal AFTER the user authenticates (`wrangler login`, OAuth), so credentials never touch this code.
 */
import { schemaToSql } from "./sql";
import type { DeployInput, DeployPlan, DeployProvider } from "./types";

export const DEFAULT_COMPAT_DATE = "2026-06-01";

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "suluk-app";
}

function wranglerConfig(input: DeployInput, name: string): string {
  const config = {
    $schema: "node_modules/wrangler/config-schema.json",
    name,
    compatibility_date: input.compatibilityDate ?? DEFAULT_COMPAT_DATE,
    compatibility_flags: ["nodejs_compat"],
    main: "worker.ts",
    // D1: the database_id is filled in after `wrangler d1 create` (step 1).
    d1_databases: [{ binding: "DB", database_name: `${name}-db`, database_id: "<run: wrangler d1 create>" }],
    // static assets (the built frontend); SPA fallback so client routes resolve.
    assets: { directory: input.assetsDir ?? "./dist/client", binding: "ASSETS", not_found_handling: "single-page-application" },
    observability: { enabled: true },
  };
  return JSON.stringify(config, null, 2) + "\n";
}

function workerEntry(input: DeployInput): string {
  const appModule = input.appModule ?? "./src/app";
  return `// CANDIDATE — generated by @suluk/deploy. The Cloudflare Worker entry.
// The Hono app is a valid Worker default export; static assets are served by the ASSETS binding (SPA fallback),
// and env.DB is the D1 database (use drizzle-orm/d1 in your handlers).
import { app } from ${JSON.stringify(appModule)};

export default app;
`;
}

/** The Cloudflare deployment provider. */
export const cloudflare: DeployProvider = {
  name: "cloudflare",
  generate(input: DeployInput): DeployPlan {
    const name = slug(input.name);
    const dbName = `${name}-db`;
    return {
      provider: "cloudflare",
      files: [
        { path: "wrangler.jsonc", content: wranglerConfig(input, name) },
        { path: "worker.ts", content: workerEntry(input) },
        { path: "schema.sql", content: schemaToSql(input.entities) },
      ],
      steps: [
        { cmd: "wrangler login", note: "authenticate with your Cloudflare account (OAuth in the browser). Or set CLOUDFLARE_API_TOKEN." },
        { cmd: `wrangler d1 create ${dbName}`, note: `create the D1 database, then paste its database_id into wrangler.jsonc (replacing the placeholder).` },
        { cmd: `wrangler d1 execute ${dbName} --file=./schema.sql --remote`, note: "apply the generated schema to the remote D1 database." },
        { cmd: "wrangler deploy", note: "deploy the Worker (the Hono API) together with the static assets (your frontend)." },
      ],
      notes: [
        "Auth happens in the terminal via `wrangler login` (OAuth) — credentials never pass through Suluk.",
        "After step 2, replace the `database_id` placeholder in wrangler.jsonc with the id `wrangler d1 create` printed.",
        `Build your frontend into "${input.assetsDir ?? "./dist/client"}" before \`wrangler deploy\` (it is served by the ASSETS binding).`,
        "Swappable by design: this is the `cloudflare` DeployProvider; other targets implement the same interface.",
      ],
    };
  },
};
