/**
 * Contract-delta → ADDITIVE migration SQL (saastarter-parity Phase 2). Given the previously-deployed entities and
 * the new contract's entities, emit the SQL to evolve D1 forward: CREATE new tables, ALTER ADD new columns. It is
 * deliberately ADDITIVE-ONLY — a removed table/column is never DROPped (that loses data; a destructive migration is
 * a human decision), only flagged as a review comment. Added columns are emitted NULLABLE (SQLite cannot ADD a
 * NOT NULL column without a default to a populated table) with a note when the new contract marked them required.
 */
import { createTable, entityColumns, tableName, type ColumnDef } from "./sql";
import type { DeployEntity } from "./types";

/** The SQL to migrate from `prev` entities to `next` entities — additive only. */
export function migrationSql(prev: DeployEntity[], next: DeployEntity[]): string {
  const prevByName = new Map(prev.map((e) => [e.name, e]));
  const nextByName = new Map(next.map((e) => [e.name, e]));
  const out: string[] = [];

  for (const entity of next) {
    const before = prevByName.get(entity.name);
    if (!before) { out.push(createTable(entity)); continue; } // a brand-new table

    const beforeCols = new Map(entityColumns(before).map((c) => [c.name, c]));
    const afterCols = entityColumns(entity);
    for (const c of afterCols) {
      if (beforeCols.has(c.name)) continue;
      // ADD COLUMN cannot be NOT NULL without a default on a populated table → emit nullable + note if it was required.
      const ddl = addColumnDdl(c);
      out.push(`ALTER TABLE ${tableName(entity)} ADD COLUMN ${ddl};`
        + (c.notNull && !c.pk ? ` -- was required in the contract; added NULLABLE (backfill, then add a CHECK/NOT NULL manually).` : ""));
    }
    const afterNames = new Set(afterCols.map((c) => c.name));
    for (const c of beforeCols.values()) {
      if (!afterNames.has(c.name)) out.push(`-- column ${tableName(entity)}.${c.name} was removed in the new contract; additive migration does NOT drop it (manual review).`);
    }
  }

  for (const entity of prev) {
    if (!nextByName.has(entity.name)) out.push(`-- table ${tableName(entity)} was removed in the new contract; additive migration does NOT drop it (manual review).`);
  }

  const body = out.length ? out.join("\n") : "-- no additive changes.";
  return `-- CANDIDATE — generated by @suluk/deploy (migrationSql). Additive-only D1 migration.\n\n${body}\n`;
}

/** ADD COLUMN DDL — always nullable (never the PK; an added column can't be the autoincrement id). */
function addColumnDdl(c: ColumnDef): string {
  return `${c.name} ${c.type}`;
}
