/**
 * Derive a Cloudflare D1 (SQLite) schema from the entities' v4 Schema Objects. D1 IS SQLite, and the Suluk
 * data floor (@suluk/drizzle) already uses sqlite-core, so this DDL matches the source with no translation.
 */
import { isReference } from "@suluk/core";
import type { SchemaOrRef } from "@suluk/core";
import type { DeployEntity } from "./types";

const lower = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

/** Map a JSON-Schema property to a SQLite column type. */
function sqliteType(prop: Record<string, unknown>): string {
  const t = Array.isArray(prop.type) ? (prop.type as string[]).find((x) => x !== "null") : prop.type;
  switch (t) {
    case "integer": return "INTEGER";
    case "number": return "REAL";
    case "boolean": return "INTEGER"; // 0/1
    default: return "TEXT"; // string, enum, object/array (JSON), null
  }
}

function createTable(entity: DeployEntity): string {
  const schema = entity.schema;
  if (isReference(schema) || typeof schema === "boolean") {
    return `-- ${entity.name}: schema is a $ref/boolean; define this table manually.`;
  }
  const props = (schema.properties ?? {}) as Record<string, Record<string, unknown>>;
  const required = new Set((schema.required as string[] | undefined) ?? []);
  const table = lower(entity.name);
  const cols: string[] = [];
  for (const [name, prop] of Object.entries(props)) {
    if (name === "id") {
      cols.push(`  id INTEGER PRIMARY KEY AUTOINCREMENT`);
      continue;
    }
    const nn = required.has(name) ? " NOT NULL" : "";
    cols.push(`  ${name} ${sqliteType(prop)}${nn}`);
  }
  if (!props.id) cols.unshift(`  id INTEGER PRIMARY KEY AUTOINCREMENT`);
  return `CREATE TABLE IF NOT EXISTS ${table} (\n${cols.join(",\n")}\n);`;
}

/** A full schema.sql for the app's entities. */
export function schemaToSql(entities: DeployEntity[]): string {
  return `-- CANDIDATE — generated by @suluk/deploy. Cloudflare D1 (SQLite) schema for this app.\n\n${entities.map(createTable).join("\n\n")}\n`;
}
