/**
 * The cockpit's DEPLOY surface (pure logic). Turns the hub document into a Cloudflare deploy plan via
 * @suluk/deploy (the swappable provider), and renders a DEPLOY.md the user follows. The extension writes the
 * files + opens a terminal; it never runs wrangler for you — deploys are consequential, and auth (`wrangler
 * login`, OAuth) happens in your terminal so credentials never touch Suluk.
 */
import type { OpenAPIv4Document } from "@suluk/core";
import { cloudflare, type DeployPlan } from "@suluk/deploy";
import { entitiesFromDoc } from "./builder";

/** Build the Cloudflare deploy plan from a v4 document (its schemas → entities). */
export function deployPlan(doc: OpenAPIv4Document): DeployPlan {
  return cloudflare.generate({
    name: doc.info?.title ?? "suluk-app",
    entities: entitiesFromDoc(doc),
    appModule: "./src/app",
    assetsDir: "./dist/client",
  });
}

/** Render the deploy plan as a DEPLOY.md the user can follow step by step. */
export function deployMarkdown(plan: DeployPlan): string {
  const steps = plan.steps.map((s, i) => `${i + 1}. \`${s.cmd}\`\n   - ${s.note}`).join("\n");
  const notes = plan.notes.map((n) => `- ${n}`).join("\n");
  const files = plan.files.map((f) => `- \`${f.path}\``).join("\n");
  return `# Deploy to Cloudflare — CANDIDATE (generated by Suluk)

Your stack is Cloudflare-native: the Hono app is the Worker, the data floor (sqlite-core) is D1, and the
built frontend is served as static assets. These files were generated for you:

${files}

## Steps (run them in the integrated terminal)

${steps}

## Notes

${notes}

> Suluk never runs these for you — \`wrangler login\` opens an OAuth flow in your browser, and deploys are
> consequential. The deployment target is swappable: this is the \`cloudflare\` provider.
`;
}
